version: '3.1'

services:
  postgress:
    image: postgres 
    environment:
      POSTGRES_USER: usepg
      POSTGRES_PASSWORD: passpg
      POSTGRES_DB: db 

    ports:
      - 5432:5432
    

  adminer:
    image: adminer 
    restart: always
    ports:
      - 8080:8080